### ISSUE TITLE
Incomplete requirements checks?

### ISSUE THREAD

**Issue by devsaurus** [Spiritdude/nodemcu-linux#3]
I tried to install NodeMCU/Linux and face some issues with missing packages.
My system currently runs an almost fresh installation of Raspbian Stretch Lite 2017-11-29.

### During `make requirements`
1. Missing `libssl1.0-dev` isn't detected, had to install manually.
  Note that LuaNode won't compile against default libssl-dev (1.1.0l).
2. ~Building CXX object CMakeFiles/luanode.dir/src/luanode.cpp.o errors out~
3. Need to apply following patch to get `LuaNode/src/luanode_stdio_linux.cpp` compile:
```patch
diff --git a/src/detail/posix/tty_stream.h b/src/detail/posix/tty_stream.h
index ccbf2b2..036f9f5 100644
--- a/src/detail/posix/tty_stream.h
+++ b/src/detail/posix/tty_stream.h
@@ -4,6 +4,7 @@
 #include "../../../deps/luacppbridge51/lcbHybridObjectWithProperties.h"
 
 #include <termios.h>
+#include <boost/array.hpp>
 #include <boost/asio.hpp>
 
 namespace LuaNode {
```

### During `make install`
1. `tar` fails because directory `misc` is missing
  Is `mkdir -p misc` sufficient?

### Success :smile: 
```
pi@rpi-z:~ $ nodemcu 
E [0.013] file modules/net/net.lua not found execute
NodeMCU/Linux 0.0.6 powered by Lua 5.1, Device ID: 10423270 / 0x9f0be6
   armv6l ARMv6-compatible processor rev 7 (v6l) (1 cores, 700-1000MHz)
   modules: node tmr file gpio i2c uart rtctime sjson bit struct math
> print(node.heap())
162758656
```

Am I missing something for `net.lua`?

**Comment by Spiritdude** [comment]
Thanks for testing on RPi (I don't own one to test):

**requirements**) added `libssl-dev`; regarding change in `tty_stream.h`, I forked `LuaNode` ... hmm, let me think how to proceed (if I include the patch conditional on RPi in NodeMCU/Linux or in my fork of LuaNode). On NanoPi NEO with Armbian:
```
% apt list --installed | grep libssl
libssl-dev/xenial-security,xenial-updates,now 1.0.2g-1ubuntu4.10 armhf [installed]
libssl1.0.0/xenial-security,xenial-updates,now 1.0.2g-1ubuntu4.10 armhf [installed]
```
When you say 'manually installed', you used 
```
apt install libssl1.0-dev
```
or compiled & installed from .tar.gz source?

**install**) 'misc/' I fixed (just contains banners but not yet used)

**success**) it should not try to load `net.lua` - I check which backend is used `arg[-1]` and it should be `luanode`, then I know to load `net-node.lua`.
- **update:** was a bug in `dofile()`, fixed now (pull again)

I began to code `net.lua` (not functional, just a skeleton) but it uses `socket` and does not support callbacks (non-blocking), then I moved to use LuaNode where things became much easier, hence just `net-node.lua` (for now I add `-node` in file name) for LuaNode-only implementations of modules. Not sure if someone wants to implement non-blocking/callback on it - so far `net` and `tmr` work good with LuaNode with the little tests I did.

I'm not yet certain about LuaNode, for now it looks good, but let's list the issues:
- `libffifb` on ARM doesn't work properly (ffi test in `startup.lua`) but works with `luajit`; `lua5.1` gives error like `luanode` - ffi functionality could become important for hardware-near(er) modules on ARM
- RPi: requires patch to compile

**Comment by Spiritdude** [comment]
I added `modules/net/net.lua` in case someone is inclined to support non-blocking/callback style later with the ordinary `socket` library (it's just a skeleton as mentioned).

**Comment by Spiritdude** [comment]
I used qemu to emulate RPi, and confirmed your discoveries - and added conditional install of `libssl-dev` in the `Makefile`.

**Comment by Spiritdude** [comment]
Included your LuaNode build patch in https://github.com/Spiritdude/LuaNode/commit/69b22186ca6bd4a5ef979a51dd46597ce3525013

Do you know why the build works otherwise, and not with latest Raspbian?

**Comment by devsaurus** [comment]
Thanks, will try to reproduce with latest commits.

> Do you know why the build works otherwise, and not with latest Raspbian?

No, not really. I'd guess that it's maybe related to the libboost version used in Raspbian: 1.62.0
Which version do you use on your reference system?

**Comment by Spiritdude** [comment]
On Armbian 5.38 (Ubuntu 16.04.3 LTS): `libboost1.58-dev`

**Comment by Spiritdude** [comment]
Best I wait for your OK, in the qemu-system-arm emulating RPi it all worked.

**Comment by Spiritdude** [comment]
Btw, can you run `nodemcu` in the `nodemcu-linux/` folder, and see if those tests perform (e.g. timer: 5x ping, 1x pong, 1x once), http-test request to httpbin.org.

**Comment by devsaurus** [comment]
The build process works flawlessly now on my RPi Z - thanks a lot for the updates! Running `nodemcu` on its own is also ok.

But the tests crash when I execute `nodemcu-linux/nodemcu`. The crash appears to be caused by `node.flashid()` due to unexpected info from df:
```
$ df -k .
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       14939312 1460476  12839408  11% /
```
`/dev/root` can't be processed by `lsblk` and `_` is nil. The return in line 95 triggers
`./modules/node/node.lua:95: attempt to index global '_' (a nil value)`

**Comment by Spiritdude** [comment]
Thanks so far, I extended `node.flashid()` to determine better the disk UUID. In case you like to test:
```
% cd <somewhere>
% nodemcu -e 'print(node.flashid())'
```
tries to determine some device to fetch the UUID from when `lsblk` fails in '.' mounted device.

**Comment by devsaurus** [comment]
Installation and the test suite work flawlessly now on my RPI-Z. Thanks a lot!
